server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://ep-royal-mode-a182d0mj-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_9qwBWFChQ3cY&sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_9qwBWFChQ3cY
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: mtgYdoc8gIO4JcaM87rcqoYhyrhQSKv4
            client-secret: lXbXFKts_lLWhzcW8DObVIqjhkrZAaoqDkvNhgl4J0fboagLmWLKWTZbKu0jlwaN
            redirect-uri: "http://localhost:5173"
            authorization-grant-type: authorization_code
        provider:
          auth0:
            issuer-uri: https://huuhoai.jp.auth0.com/
      resourceserver:
        jwt:
          issuer-uri: https://huuhoai.jp.auth0.com/
          audiences: https://huuhoai.jp.auth0.com/api/v2/

