server:
  port: 8081
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id:
            client-secret:
            redirect-uri: "http://localhost:5173"
            authorization-grant-type: authorization_code
        provider:
          auth0:
            issuer-uri: https://huuhoai.jp.auth0.com/
      resourceserver:
        jwt:
          issuer-uri: https://huuhoai.jp.auth0.com/
          audiences: https://huuhoai.jp.auth0.com/api/v2/
          jwk-set-uri: https://huuhoai.jp.auth0.com/.well-known/jwks.json

